export default [
  {
    name: "Araminta",
    path: "../assets/logos/araminta.svg",
    alt: "Araminta Logo",
    background: "",
    id: 1,
  },
  {
    name: "Academy United",
    path: "../assets/logos/academyUnited.svg",
    alt: "Academy United Logo",
    background: "",
    id: 2,
  },
  {
    name: "Almshad Group",
    path: "../assets/logos/almshadGroup.svg",
    alt: "Almshad Group Logo",
    background: "",
    id: 3,
  },
  {
    name: "Bdaya",
    path: "../assets/logos/bdaya.svg",
    alt: "Bdaya Logo",
    background: "",
    id: 4,
  },
  {
    name: "Climatology",
    path: "../assets/logos/climatology.svg",
    alt: "Climatology Logo",
    background: "",
    id: 5,
  },
  {
    name: "Compass Academy",
    path: "../assets/logos/compassAcademy.svg",
    alt: "Compass Academy Logo",
    background: "",
    id: 6,
  },
  {
    name: "Fanar",
    path: "../assets/logos/fanar.svg",
    alt: "Fanar Logo",
    background: "",
    id: 7,
  },
  {
    name: "Fbm",
    path: "../assets/logos/fbm.svg",
    alt: "FBM Logo",
    background: "",
    id: 8,
  },
  {
    name: "FunFit House",
    path: "../assets/logos/funFitHouse.svg",
    alt: "FunFit House Logo",
    background: "",
    id: 9,
  },
  {
    name: "Ghazala",
    path: "../assets/logos/ghazala.svg",
    alt: "Ghazala Logo",
    background: "",
    id: 10,
  },
  {
    name: "Lahaye",
    path: "../assets/logos/lahaye.svg",
    alt: "Lahaye Logo",
    background: "",
    id: 11,
  },
  {
    name: "Leen Olives",
    path: "../assets/logos/leenOlives.svg",
    alt: "Leen Olives Logo",
    background: "",
    id: 12,
  },
  {
    name: "Lobna",
    path: "../assets/logos/lobna.svg",
    alt: "Lobna Logo",
    background: "",
    id: 13,
  },
  {
    name: "Mashawir",
    path: "../assets/logos/mashawir.svg",
    alt: "Mashawir Logo",
    background: "",
    id: 14,
  },
  {
    name: "Mnjl",
    path: "../assets/logos/mnjl.svg",
    alt: "Mnjl Logo",
    background: "",
    id: 15,
  },
  {
    name: "Rahilah",
    path: "../assets/logos/rahilah.svg",
    alt: "Rahilah Logo",
    background: "",
    id: 16,
  },
  {
    name: "Sd Contracting",
    path: "../assets/logos/sdContracting.svg",
    alt: "Sd Contracting Logo",
    background: "",
    id: 17,
  },
  {
    name: "Waghah",
    path: "../assets/logos/waghah.svg",
    alt: "Waghah Logo",
    background: "",
    id: 18,
  },
  {
    name: "Wassil",
    path: "../assets/logos/wassil.svg",
    alt: "Wassil Logo",
    background: "",
    id: 19,
  },
  {
    name: "ZdMed",
    path: "../assets/logos/zdMed.svg",
    alt: "ZD MED Logo",
    background: "",
    id: 20,
  }
];

