export default [
  {
    name: "Araminta",
    path: "../assets/logos/araminta.svg",
    alt: "Araminta Logo",
    background: "#E5C59E",
    id: 1,
  },
  {
    name: "FunFit House",
    path: "../assets/logos/funFitHouse.svg",
    alt: "FunFit House Logo",
    background: "#F07831",
    id: 2,
  },
  {
    name: "Bdaya",
    path: "../assets/logos/bdaya.svg",
    alt: "Bdaya Logo",
    background: "#2A353B",
    id: 3,
  },
  {
    name: "Wassil",
    path: "../assets/logos/wassil.svg",
    alt: "Wassil Logo",
    background: "#19518D",
    id: 4,
  },
  {
    name: "shifaa",
    path: "../assets/logos/shifaa.svg",
    alt: "Shifaa Logo",
    background: "#AAFBBE",
    id: 6,
  },
  {
    name: "kigo",
    path: "../assets/logos/kigo.svg",
    alt: "Kigoo Logo",
    background: "#E8E214",
    id: 8,
  },
  {
    name: "Mnjl",
    path: "../assets/logos/mnjl.svg",
    alt: "Mnjl Logo",
    background: "#2A5841",
    id: 9,
  },
  {
    name: "Lobna",
    path: "../assets/logos/lobna.svg",
    alt: "Lobna Logo",
    background: "#E5978B",
    id: 10,
  },
  {
    name: "Leen Olives",
    path: "../assets/logos/leenOlives.svg",
    alt: "Leen Olives Logo",
    background: "#BABD7C",
    id: 11,
  },
  {
    name: "Mashawir",
    path: "../assets/logos/mashawir.svg",
    alt: "Mashawir Logo",
    background: "#00C8F3",
    id: 13,
  },
  {
    name: "Sd Contracting",
    path: "../assets/logos/sdContracting.svg",
    alt: "Sd Contracting Logo",
    background: "#FCF8EC",
    id: 14,
  },
  {
    name: "Rahilah",
    path: "../assets/logos/rahilah.svg",
    alt: "Rahilah Logo",
    background: "#00919B",
    id: 15,
  },
  {
    name: "Fbm",
    path: "../assets/logos/fbm.svg",
    alt: "FBM Logo",
    background: "",
    id: 16,
  },
  {
    name: "ZdMed",
    path: "../assets/logos/zdMed.svg",
    alt: "ZD MED Logo",
    background: "#1A4877",
    id: 17,
  },
  {
    name: "Waghah",
    path: "../assets/logos/waghah.svg",
    alt: "Waghah Logo",
    background: "#99B073",
    id: 18,
  },
  {
    name: "Lahaye",
    path: "../assets/logos/lahaye.svg",
    alt: "Lahaye Logo",
    background: "#0E0E0E",
    id: 19,
  },
  {
    name: "Compass Academy",
    path: "../assets/logos/compassAcademy.svg",
    alt: "Compass Academy Logo",
    background: "#FCF8EC",
    id: 20,
  },
  {
    name: "pnp",
    path: "../assets/logos/pnp.svg",
    alt: "PNP Logo",
    background: "#FCF8EC",
    id: 21,
  },
  {
    name: "Ghazala",
    path: "../assets/logos/ghazala.svg",
    alt: "Ghazala Logo",
    background: "#470D21",
    id: 22, // Duplicate ID, assuming it's supposed to be 23
  },
  {
    name: "middle east",
    path: "../assets/logos/middleEast.svg",
    alt: "Middle East Logo",
    background: "#04539B",
    id: 24,
  }
].sort((a, b) => a.id - b.id);
